/*
 * generated by Xtext
 */
package b.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import b.ui.internal.BActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BActivator.getInstance().getInjector(BActivator.B_B);
	}
	
}
