/*
 * generated by Xtext
 */
package b.ui.contentassist

import b.ui.contentassist.AbstractBProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class BProposalProvider extends AbstractBProposalProvider {
}
