/**
 * generated by Xtext
 */
package a.validation;

import a.validation.AbstractAValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class AValidator extends AbstractAValidator {
}
