/*
 * generated by Xtext
 */
package a.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AUiModule extends a.ui.AbstractAUiModule {
	public AUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
