grammar b.B with org.eclipse.xtext.common.Terminals

generate b "http://www.B.b"
import "http://www.A.a" as a

Model:
	'package' name=QualifiedName
	imports+=Import*
	greetings+=ReferencedGreeting*;

Import:
	'import' importedNamespace=QualifiedNameWithWildcard;

QualifiedNameWithWildcard:
	QualifiedName '.*'?;

ReferencedGreeting:
	'g: ' name=[a::Greeting|QualifiedName];

QualifiedName:
	ID ('.' ID)*;
