/*
* generated by Xtext
*/
package b;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class BStandaloneSetup extends BStandaloneSetupGenerated{

	public static void doSetup() {
		new BStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

