/*
 * generated by Xtext
 */
package a.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import a.ui.internal.AActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AActivator.getInstance().getInjector(AActivator.A_A);
	}
	
}
