/*
 * generated by Xtext
 */
package a;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ARuntimeModule extends a.AbstractARuntimeModule {

}
