/*
* generated by Xtext
*/
package a;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AStandaloneSetup extends AStandaloneSetupGenerated{

	public static void doSetup() {
		new AStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

