/*
 * generated by Xtext
 */
package b.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BUiModule extends b.ui.AbstractBUiModule {
	public BUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
