/*
* generated by Xtext
*/
package a;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class AUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return a.ui.internal.AActivator.getInstance().getInjector("a.A");
	}
	
}
