/**
 * generated by Xtext
 */
package b.validation;

import b.validation.AbstractBValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class BValidator extends AbstractBValidator {
}
