/*
 * generated by Xtext
 */
package a.ui.contentassist

import a.ui.contentassist.AbstractAProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class AProposalProvider extends AbstractAProposalProvider {
}
