/*
* generated by Xtext
*/
package b;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class BUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return b.ui.internal.BActivator.getInstance().getInjector("b.B");
	}
	
}
